# Top 8 Powerful Functions in Python for Date Analysis

1.Groupby

2.Pivot_Table

3.Aggregate

4.Cross_tab

5.Concat

6.Apply

7.Lambda

8.Del(Keyword)

# 1.Groupby Function

In [2]:
import pandas as pd

In [27]:
insurance_date=pd.read_csv("insurance.csv.csv")
insurance_date

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## Perform Initial Analysis

In [5]:
insurance_date.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
insurance_date.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [7]:
insurance_date.shape

(1338, 7)

In [8]:
insurance_date.describe(include="all")

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN
mean,39.207025,NaN,30.663397,1.094918,NaN,NaN,13270.422265
std,14.049960,NaN,6.098187,1.205493,NaN,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,NaN,1121.873900
25%,27.000000,NaN,26.296250,0.000000,NaN,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.033000
75%,51.000000,NaN,34.693750,2.000000,NaN,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,NaN,63770.428010

In [9]:
insurance_date["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

## Pull up the Average Insurance Charges Based on region

In [10]:
insurance_date.groupby(by="region")["charges"].mean().round().sort_values() #Chain of Methods

region
southwest    12347.0
northwest    12418.0
northeast    13406.0
southeast    14735.0
Name: charges, dtype: float64

## Pull up the Average Insurance Charges Based on region and Sex

## Discrete and Continous Date

* Discrete - Just Countable/Can't be segmented

* continous - Measurable /Have Units/Can also be segmented

In [11]:
insurance_date.groupby(by=["region","sex"])["charges"].mean().round().sort_values(ascending=False)

region     sex
southeast  male      15880.0
northeast  male      13854.0
southeast  female    13500.0
southwest  male      13413.0
northeast  female    12953.0
northwest  female    12480.0
           male      12354.0
southwest  female    11274.0
Name: charges, dtype: float64

# Pivot Table

In [12]:
pd.pivot_table(data=insurance_date,values="charges",index="region",columns=["sex"]).round() # Presentable comparing 2 categorical features vs 1 continous

sex         female     male
region
northeast  12953.0  13854.0
northwest  12480.0  12354.0
southeast  13500.0  15880.0
southwest  11274.0  13413.0

# Aggregate

In [13]:
insurance_date.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Find out the average insurance charges based on region.

In [20]:
insurance_date.groupby(by=["region","sex"])["charges"].agg(func=["mean","min","max","sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

In [ ]:
insurance_date.agg()

# Crosstab

In [21]:
insurance_date.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## How many Smokers and Non Smokers based on region ?

In [29]:
pd.crosstab(index=insurance_date["region"],columns=insurance_date["smoker"],margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

## Note it !

In [9]:
insurance_date.age

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [11]:
insurance_date[["age","region"]]

      age     region
0      19  southwest
1      18  southeast
2      28  southeast
3      33  northwest
4      32  northwest
...   ...        ...
1333   50  northwest
1334   18  northeast
1335   18  southeast
1336   21  southwest
1337   61  northwest

[1338 rows x 2 columns]

# Concat

In [4]:
sales_data_2017=pd.read_csv("sales_transactions_2017.csv")
sales_data_2018=pd.read_csv("sales_transactions_2018.csv")
sales_data_2019=pd.read_csv("sales_transactions_2019.csv")

In [5]:
sales_full_data=pd.concat(objs=[sales_data_2017,sales_data_2018,sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [7]:
sales_full_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [8]:
sales_full_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

# Level 4.5/5 Complexity Challenge.

# Merge function()Explore - left join,right join,inner join,outer join.

# Apply

In [12]:
insurance_date

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## Create a new column in the same dateframe with the name "Eligibilty Criteria" where if age is > 20 , say Eligibilty else Not.

In [14]:
insurance_date[insurance_date["age"] > 20]

      age     sex     bmi  children smoker     region      charges
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
...   ...     ...     ...       ...    ...        ...          ...
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1172 rows x 7 columns]

In [15]:
def get_age(x):
    if x > 20:
        return "Eligibile"
    else:
        return "Not Eligibile"

In [28]:
insurance_date["Eligibilty Criteria"]=insurance_date["age"].apply(func=get_age)
insurance_date

,age,sex,bmi,children,smoker,region,charges,Eligibilty Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligibile
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligibile
2,28,male,33.000,3,no,southeast,4449.46200,Eligibile
3,33,male,22.705,0,no,northwest,21984.47061,Eligibile
4,32,male,28.880,0,no,northwest,3866.85520,Eligibile
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligibile
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligibile
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligibile
1336,21,female,25.800,0,no,southwest,2007.94500,Eligibile
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligibile

# Lambda Function

* Anonymous Function/Nameless Function

In [29]:
insurance_date["EC"]=insurance_date["age"].apply(lambda x: "Eligibile" if x>20 else "Not Eligibile")
insurance_date

,age,sex,bmi,children,smoker,region,charges,Eligibilty Criteria,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligibile,Not Eligibile
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligibile,Not Eligibile
2,28,male,33.000,3,no,southeast,4449.46200,Eligibile,Eligibile
3,33,male,22.705,0,no,northwest,21984.47061,Eligibile,Eligibile
4,32,male,28.880,0,no,northwest,3866.85520,Eligibile,Eligibile
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligibile,Eligibile
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligibile,Not Eligibile
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligibile,Not Eligibile
1336,21,female,25.800,0,no,southwest,2007.94500,Eligibile,Eligibile
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligibile,Eligibile

## Explore List Comprehension 3 examples

## Explore Lambda - Map,Filter,Query.

# Delete Function

In [33]:
insurance_date

,age,sex,bmi,children,smoker,region,charges,Eligibilty Criteria,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligibile,Not Eligibile
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligibile,Not Eligibile
2,28,male,33.000,3,no,southeast,4449.46200,Eligibile,Eligibile
3,33,male,22.705,0,no,northwest,21984.47061,Eligibile,Eligibile
4,32,male,28.880,0,no,northwest,3866.85520,Eligibile,Eligibile
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligibile,Eligibile
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligibile,Not Eligibile
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligibile,Not Eligibile
1336,21,female,25.800,0,no,southwest,2007.94500,Eligibile,Eligibile
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligibile,Eligibile

In [34]:
del insurance_date["EC"]

In [35]:
insurance_date

,age,sex,bmi,children,smoker,region,charges,Eligibilty Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligibile
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligibile
2,28,male,33.000,3,no,southeast,4449.46200,Eligibile
3,33,male,22.705,0,no,northwest,21984.47061,Eligibile
4,32,male,28.880,0,no,northwest,3866.85520,Eligibile
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligibile
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligibile
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligibile
1336,21,female,25.800,0,no,southwest,2007.94500,Eligibile
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligibile

# THE END