# 1.	Write a program to take a name and age from the user and print a greeting message.

In [3]:
user_name=input("Enter your Name")
user_age=input("Enter your Age")
print("welcome {} your age is {} years old.".format(user_name,user_age))

Enter your Name Arunkumar
Enter your Age 21

welcome Arunkumar your age is 21 years old.

# 2.Create a list of numbers and print only even numbers using a for loop.

In [16]:
A=range(1,31)
even_numbers=[]

for i in A:
    if i%2 == 0:
        even_numbers.append(i)

even_numbers

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

# 3.Write a program that handles division by zero using try-except.

In [30]:
numerator = int(input("Enter the Numerator"))
den = int(input("Enter the denominator"))

try:
    results = numerator/den
    print(results)

except ZeroDivisionError:
    print("Invaild Entry ! Enter the number other than 0")

print("Program Ended")

Enter the Numerator 21
Enter the denominator 0

Invaild Entry ! Enter the number other than 0
Program Ended

# 4.Given a string, count how many vowels it has.

In [41]:
vowels =("a","e","i","o","u")
count = 0

user_input=input("Enter your Name").lower()
for i in user_input:
    if i in vowels:
        count=count+1
print("Total numbers of Vowels are:",count)

Enter your Name Arunkumar

Total numbers of Vowels are: 4

# 5.Reverse a list without using built-in functions.

In [2]:
original_list=[1,2,3,4,5]
updated_list=[]

i=len(original_list)-1

while i>=0:
    updated_list.append(original_list[i])
    i = i-1

updated_list

[5, 4, 3, 2, 1]

# 6.Create a dictionary with at least 5 key-value pairs and print them.

In [5]:
school_marks={"Name":["Arunkumar","Enian","Naresh","Tarun","Karthi"],"Marks":[477,450,500,550,515]}
print(school_marks)

{'Name': ['Arunkumar', 'Enian', 'Naresh', 'Tarun', 'Karthi'], 'Marks': [477, 450, 500, 550, 515]}

In [ ]:
school_marks.t

# 7.Write a Pandas code to read a CSV and print the top 5 rows.

In [6]:
import pandas as pd

In [9]:
insurance_date=pd.read_csv("insurance.csv.csv")
insurance_date

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [10]:
insurance_date.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# 8.Create a DataFrame from a Python dictionary.

In [21]:
pd.DataFrame(school_marks)

        Name  Marks
0  Arunkumar    477
1      Enian    450
2     Naresh    500
3      Tarun    550
4     Karthi    515

# 9.Replace all missing values in a DataFrame with the column’s mean.

In [25]:
employee_date=pd.read_csv("employee_data (1).csv")
employee_date

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [27]:
employee_date["Salary"].mean()

np.float64(62500.0)

In [30]:
employee_date["Salary"].fillna(value=employee_date["Salary"].mean(),inplace=True)

In [31]:
employee_date

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

In [35]:
employee_date.drop_duplicates(inplace=True)

In [36]:
employee_date

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [37]:
employee_date["Age"]

0    29.0
1    31.0
2     NaN
3    29.0
4    28.0
5    35.0
6    40.0
Name: Age, dtype: float64

In [41]:
employee_date["Age"].fillna(value=27,inplace=True)
employee_date

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew  27.0    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

# 10.Filter rows in a DataFrame where the "Age" column is greater than 30.

In [45]:
employee_date[employee_date["Age"]>30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022

In [47]:
insurance_date[insurance_date["age"]>30]

      age     sex     bmi  children smoker     region      charges
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
7      37  female  27.740         3     no  northwest   7281.50560
...   ...     ...     ...       ...    ...        ...          ...
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1337   61  female  29.070         0    yes  northwest  29141.36030

[894 rows x 7 columns]

# THE END