# Chapter -01: Getting & Knowing your Data

In [3]:
import pandas as pd

In [47]:
hotel_order_details=pd.read_csv(filepath_or_buffer="data.tsv.txt",sep="\t")
hotel_order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### 1.1 Perform Initial Analysis

In [5]:
# Function - ()
# Attribute

In [6]:
hotel_order_details.shape

(4622, 5)

### Terminology Alert

* Rows - Observations/Record.
* Column - Features/Parameters

In [9]:
hotel_order_details.isnull().sum() #Chain of functions, Chain of commands

    order_id             0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [14]:
hotel_order_details.dtypes

    order_id           int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [15]:
hotel_order_details.describe(include="all")

            order_id     quantity     item_name choice_description item_price
count    4622.000000  4622.000000          4622               3376       4622
unique           NaN          NaN            50               1043         78
top              NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq             NaN          NaN           726                134        730
mean      927.254868     1.075725           NaN                NaN        NaN
std       528.890796     0.410186           NaN                NaN        NaN
min         1.000000     1.000000           NaN                NaN        NaN
25%       477.250000     1.000000           NaN                NaN        NaN
50%       926.000000     1.000000           NaN                NaN        NaN
75%      1393.000000     1.000000           NaN                NaN        NaN
max      1834.000000    15.000000           NaN                NaN        NaN

## 1.2 Find out the Items sold in the Restaurent

In [17]:
hotel_order_details.nunique()

    order_id          1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [20]:
print(hotel_order_details["item_name"].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

## 1.3 Give me the list of Top 5 Selling Items

In [33]:
hotel_order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending =False).head(10)  # Chain methods

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

## 1.3 Give me the list of Least 5 Selling Items

In [32]:
hotel_order_details.groupby(by="item_name")["quantity"].sum().sort_values().head(10)  # Chain methods

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Steak Salad                          4
Bowl                                 4
Burrito                              6
Carnitas Salad Bowl                  6
Veggie Salad                         6
Name: quantity, dtype: int64

# Date Cleaning

In [34]:
hotel_order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [35]:
hotel_order_details.dtypes

    order_id           int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [ ]:
hotel_order_details["item_price"]=hotel_order_details["item_price"].str.replace("$","").astype(float) # Chain of Methods

In [54]:
hotel_order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [55]:
hotel_order_details.dtypes

    order_id            int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [56]:
hotel_order_details.describe()

           order_id     quantity   item_price
count   4622.000000  4622.000000  4622.000000
mean     927.254868     1.075725     7.464336
std      528.890796     0.410186     4.245557
min        1.000000     1.000000     1.090000
25%      477.250000     1.000000     3.390000
50%      926.000000     1.000000     8.750000
75%     1393.000000     1.000000     9.250000
max     1834.000000    15.000000    44.250000

In [58]:
hotel_order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

### Task

In [63]:
top_5_selling = hotel_order_details.groupby(by="item_name")["item_price"].sum().sort_values(ascending =False).head(5)

In [64]:
top_5_selling

item_name
Chicken Bowl           7342.73
Chicken Burrito        5575.82
Steak Burrito          3851.43
Steak Bowl             2260.19
Chips and Guacamole    2201.04
Name: item_price, dtype: float64

In [65]:
top_5_selling.sum()

np.float64(21231.21)

# Chapter 3 - Pandas Date Structure 

* 1D - Series

* 2D - Dateframe

In [75]:
pd.Series(data=[4,5,6,7,8])

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [9]:
pd.DataFrame({"Name":["Arun","Karthi","Enian","Naresh","Tarun"],"Ergomters Timing":["6.48","6.58","6.56","6.40","6.30"],"Height":["190Cm","175Cm","185Cm","184Cm","188Cm"],"Weight":[85,70,60,85,90]})

     Name Ergomters Timing Height  Weight
0    Arun             6.48  190Cm      85
1  Karthi             6.58  175Cm      70
2   Enian             6.56  185Cm      60
3  Naresh             6.40  184Cm      85
4   Tarun             6.30  188Cm      90

# Chapter - 4 Filtering & Selection & Sorting

In [1]:
import pandas as pd

In [2]:
euro_2012_date=pd.read_csv("Euro_2012_stats_TEAM.csv")
euro_2012_date

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [3]:
euro_2012_date.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [16]:
### pd.set_option('display.max_columns',None) - For more details show of columns

In [5]:
filterred_euro=euro_2012_date[["Team","Goals","Yellow Cards", "Red Cards"]]
filterred_euro

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [8]:
filterred_euro["Yellow Cards"]

0      9
1      7
2      4
3      5
4      6
5      4
6      9
7     16
8      5
9      7
10    12
11     6
12     6
13    11
14     7
15     5
Name: Yellow Cards, dtype: int64

### 4.1 Top 5 Yellow Cards Team

In [9]:
filterred_euro.sort_values(by ="Yellow Cards",ascending=False).head()

        Team  Goals  Yellow Cards  Red Cards
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0
0    Croatia      4             9          0
6     Greece      5             9          1

### 4.2 List the teams which has got Red cards

In [11]:
filterred_euro[filterred_euro["Red Cards"] == 1]

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

### 4.3 List teams which has got more than 8 Yellow Cards

In [13]:
filterred_euro[filterred_euro["Yellow Cards"] >=8]

        Team  Goals  Yellow Cards  Red Cards
0    Croatia      4             9          0
6     Greece      5             9          1
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0

### Chapter 05 - How to deal with Missing Values

In [14]:
import pandas as pd

In [22]:
proitbridge_employee_date=pd.read_csv("employee_data.csv")
proitbridge_employee_date

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

## Level 1 Date Cleaning

### Always Recommended : I will call to my client, and check with him if he can give the right data - Great!!!

Incase,client is asking us to perform the Date cleaning operations.

### Step 1 : Remove Duplicate entries/records

In [26]:
proitbridge_employee_date.drop_duplicates(inplace=True) # The complete operations will impact the original Dateset.

In [27]:
proitbridge_employee_date

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [31]:
proitbridge_employee_date.shape

(7, 5)

### Step 2: Find out the Null Entries

In [29]:
proitbridge_employee_date.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [32]:
proitbridge_employee_date.dropna(inplace=True)

In [34]:
proitbridge_employee_date

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [35]:
proitbridge_employee_date.shape

(4, 5)

### Step 3: Record in a Document

* Client gave totally 7 Obseravations out of which 3 entries are removed because those records do not have complete information.

### Step 4: Get Approval
* Send this to client and get the approval to proceed for Model Building or Model Training.

In [37]:
proitbridge_employee_date.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

## Level 2 of Date Cleaning

In [1]:
import pandas as pd

In [ ]:
pd.read_csv() #You cannot import multiple sheets if it's in one CSV file, you need to have seperate CSV file.

In [ ]:
pd.read_excel() # You can import multiple sheets.