# TASK 1 - Python Date Structures

## List

### 1.Append

In [12]:
user_number=[89,90,78,56]
user_number.append(25)
print(user_number)

[89, 90, 78, 56, 25]

In [13]:
fruits=["apple","strawberry","Rice"]
fruits.append("Milk")
print(fruits)

['apple', 'strawberry', 'Rice', 'Milk']

### 2.Insert

In [17]:
colors = ["red", "green", "yellow"]
colors.insert(1,"blue")
print(colors)

['red', 'blue', 'green', 'yellow']

### 3.Remove

In [18]:
animals=["dog","cat","rabbit"]
animals.remove("cat")
print(animals)

['dog', 'rabbit']

### 4.Pop

In [26]:
numbers=[21,31,41,51,61]
popped_value=numbers.pop(-1)
print("Popped value:" ,popped_value)
print("Updated list:",numbers)

Popped value: 61
Updated list: [21, 31, 41, 51]

### 5.Sort

In [30]:
list_1=[12, 4, 67, 1]
list_1.sort()
print(list_1)

[1, 4, 12, 67]

In [32]:
name_list=["Zyed","Dhanjayan","Enian","Naresh","Tarunprasad","Arunkumar","Karthi"]
name_list.sort()
print(name_list)

['Arunkumar', 'Dhanjayan', 'Enian', 'Karthi', 'Naresh', 'Tarunprasad', 'Zyed']

### 6.Reverse

In [37]:
num_list=[1,2,3,45,6,7,44,22]
num_list.reverse()
print(num_list)

[22, 44, 7, 6, 45, 3, 2, 1]

### 7.Index

In [38]:
fruits

['apple', 'strawberry', 'Rice', 'Milk']

In [39]:
fruits[2]

'Rice'

### 8.Count

In [40]:
count_list=[2, 3, 2, 5, 2, 7]

In [41]:
count_list.count(2)

3

### 9.Extend

In [55]:
a=[1,2,3,4,5,6,7]
b=[22,33,44,55,66]

In [56]:
a.extend(b)

In [57]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 22, 33, 44, 55, 66]

### 10.Clear

In [58]:
que=[1,2,3,4,5,6]
que.clear()
print(que)

[]

## Set

### 1.Add

In [83]:
set_fruits={"Apple","Mango","strawberry"}
set_fruits.add("Pineapple")
print(set_fruits)

{'strawberry', 'Pineapple', 'Apple', 'Mango'}

In [84]:
set_fruits={"Apple","Mango","strawberry"}
set_fruits.add("Apple")
print(set_fruits)

{'strawberry', 'Apple', 'Mango'}

### 2.Update

In [17]:
s={1,2,3,4}
s.update([8,9,6,5])
print(s)

{1, 2, 3, 4, 5, 6, 8, 9}

In [18]:
s.update("abc")
print(s)

{1, 2, 3, 4, 5, 6, 'a', 8, 9, 'b', 'c'}

### 3.Remove

In [19]:
remove_set={5,6,7,8}
remove_set.remove(7)
print(remove_set)

{8, 5, 6}

### 4.Discard

In [41]:
remove_set.discard(10)
print(remove_set)

{8, 6}

### 5.Pop

In [45]:
h={1,2,3,4,5}
h.pop()
print(h)

{2, 3, 4, 5}

In [46]:
y={100}
y.pop()
print(y)

set()

### 6.Clear

In [47]:
o={89,99}
o.clear()
print(o)

set()

In [48]:
o.add(10)
print(o)

{10}

In [49]:
q1={1,2,3}
q2=q1.copy()
q3=q1

In [50]:
q3

{1, 2, 3}

In [51]:
q2

{1, 2, 3}

In [52]:
q1

{1, 2, 3}

### 7.Union

In [60]:
print({1,2,3,4,5}.union({2,3,4,5,6,7,8,9}))

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [63]:
print({22,33}.union({88,99},{45,66}))

{33, 66, 99, 22, 88, 45}

### 8.Intersection

In [62]:
print({1,2,3,4,5}.intersection({2,3,4}))

{2, 3, 4}

### 9.Difference

In [64]:
print({2,3,4,5,}.difference({3,4}))

{2, 5}

### 10.Symmetric_difference

In [66]:
print({1,2,3}.symmetric_difference({2,3}))

{1}

In [67]:
print({1,2}.symmetric_difference({1,2}))

set()

### 11.issubset

In [73]:
print({1,2}.issubset({1,2,3,4}))

True

### 12.issuperset

In [74]:
print({1,2,3,4}.issuperset({3}))

True

In [75]:
print({1,2,3,4}.issuperset({1,2,3}))

True

### 13.isdisjoint

In [76]:
print({1,2,3}.isdisjoint({4}))

True

In [77]:
print({1,2,3}.isdisjoint({1}))

False

## Tuples

### 1.Count

In [78]:
nums = (1, 3, 5, 3, 3, 7, 1)

In [79]:
nums.count(3)

3

### 2.Index

In [82]:
fruits_0 = ('apple', 'banana', 'mango', 'orange')
fruits_0.index("mango")

2

## Dictioary

### 1.Get

In [133]:
student = {"name": "Alex", "age": 20}
student.get("grade")

In [134]:
student.get("name")

'Alex'

In [135]:
student.get("grade")

### 2.Keys

In [92]:
student = {"name": "Alex", "age": 20}

In [93]:
student.keys()

dict_keys(['name', 'age'])

### 3.Values

In [136]:
student = {"name": "Alex", "age": 20}

In [137]:
student.values()

dict_values(['Alex', 20])

### 4.Items

In [138]:
d = {"x": 1, "y": 2}

In [139]:
d.items()

dict_items([('x', 1), ('y', 2)])

### 5.Update

In [140]:
g={"a":1,"b":2}

In [141]:
g.update({"c":3})
print(g)

{'a': 1, 'b': 2, 'c': 3}

### 6.Pop

In [142]:
g.pop("a")

1

In [143]:
g

{'b': 2, 'c': 3}

### 7.Popitem

In [144]:
g={"a":1,"k":3,"I":8}

In [145]:
g.popitem()

('I', 8)

In [146]:
g

{'a': 1, 'k': 3}

### 8.Setdefault

In [147]:
d={"name":"Arunkumar.M"}

In [148]:
d.setdefault("age",21)

21

In [149]:
d

{'name': 'Arunkumar.M', 'age': 21}

### 9.Clear

In [150]:
p = {"a": 1, "b": 2}

In [151]:
p

{'a': 1, 'b': 2}

In [152]:
p.clear()

In [153]:
p

{}

### 10.Copy

In [128]:
a={"Name":"Arun","Age":21}

In [129]:
b=a

In [130]:
b

{'Name': 'Arun', 'Age': 21}

In [131]:
c=a.copy()

In [132]:
c

{'Name': 'Arun', 'Age': 21}

# TASK - 02 DATEFRAMES

## 01

In [11]:
Rowing_ergomerter_timing={"Name" : ["Enian","Naresh","Arun","Ekshith","Tarun","Karthi"],"Timing" : [6.58,6.40,6.48,6.37,6.35,6.58],"Height":["185CM","185CM","190CM","190CM","188CM","175CM"] }

In [12]:
Rowing_ergomerter_timing

{'Name': ['Enian', 'Naresh', 'Arun', 'Ekshith', 'Tarun', 'Karthi'],
 'Timing': [6.58, 6.4, 6.48, 6.37, 6.35, 6.58],
 'Height': ['185CM', '185CM', '190CM', '190CM', '188CM', '175CM']}

In [13]:
import pandas as pd 

pd.DataFrame(Rowing_ergomerter_timing)

      Name  Timing Height
0    Enian    6.58  185CM
1   Naresh    6.40  185CM
2     Arun    6.48  190CM
3  Ekshith    6.37  190CM
4    Tarun    6.35  188CM
5   Karthi    6.58  175CM

## 02

In [14]:
item_in_stock={"Item":["Rice","Tomato","Milk","Curd","Icecream"],"Stock":["500Kg","10","5L","3L","15Boxes"]}

In [15]:
pd.DataFrame(item_in_stock)

       Item    Stock
0      Rice    500Kg
1    Tomato       10
2      Milk       5L
3      Curd       3L
4  Icecream  15Boxes

## 03

In [29]:
students_marks={"Name":["Arun","Naresh","Enian","Karthi"],"Social science":[88,80,90,85]}

In [30]:
pd.DataFrame(students_marks)

     Name  Social science
0    Arun              88
1  Naresh              80
2   Enian              90
3  Karthi              85

# THE END ---------------------------------------------------------------------