# Task 1 Data Cleaning

In [2]:
import pandas as pd

In [2]:
sales_data_2017=pd.read_csv("sales_transactions_2017.csv")
sales_data_2018=pd.read_csv("sales_transactions_2018.csv")
sales_data_2019=pd.read_csv("sales_transactions_2019.csv")

In [3]:
sales_full_data=pd.concat([sales_data_2017,sales_data_2018,sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [4]:
sales_edited=pd.read_csv("sales_edited.csv")
sales_edited

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [5]:
sales_full_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [6]:
sales_full_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [7]:
sales_full_data.drop_duplicates(inplace=True)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [8]:
sales_full_data.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

In [9]:
del sales_full_data["Gross"]
del sales_full_data["Disc"]
del sales_full_data["Voucher Amount"]

In [10]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40"

In [11]:
sales_full_data.isna().sum()

Date       204
Voucher    170
Party       35
Product    204
Qty        170
Rate       171
dtype: int64

In [12]:
sales_full_data["Voucher"]=sales_full_data["Voucher"].str.replace("Sal:","")
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40"

In [13]:
sales_full_data.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [14]:
sales_edited

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [15]:
sales_full_data.drop_duplicates(inplace=True)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40"

In [16]:
sales_full_data.isnull().sum()

Date       204
Voucher    170
Party       35
Product    204
Qty        170
Rate       171
dtype: int64

In [17]:
sales_full_data.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [18]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40"

In [19]:
sales_full_data.drop([19174,19175], inplace=True)

In [20]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16

In [21]:
sales_full_data[sales_full_data['Product'].isna()]

      Date  Voucher               Party Product         Qty        Rate
11     NaN      NaN              #NAME?     NaN         NaN         NaN
53     NaN      NaN                  KR     NaN         NaN         NaN
77     NaN      NaN           IC CENTRE     NaN         NaN         NaN
79     NaN      NaN     LAKSHMIMEDICALS     NaN         NaN         NaN
104    NaN      NaN            LS VGIRI     NaN         NaN         NaN
...    ...      ...                 ...     ...         ...         ...
16890  NaN      NaN             ADY MIX     NaN         NaN         NaN
17015  NaN      NaN  HARI-SRIKALAHASTHI     NaN         NaN         NaN
18033  NaN      NaN                  RU     NaN         NaN         NaN
18347  NaN  Total                   NaN     NaN  274,408.60  674,780.19
18601  NaN      NaN                RESH     NaN         NaN         NaN

[202 rows x 6 columns]

In [22]:
sales_full_data.dropna(subset="Date",inplace=True)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16

In [23]:
sales_full_data[sales_full_data['Product'].isna()]

Empty DataFrame
Columns: [Date, Voucher, Party, Product, Qty, Rate]
Index: []

In [24]:
sales_full_data["Party"].isna().sum()

np.int64(0)

In [25]:
sales_full_data[sales_full_data["Rate"].isna()]

           Date Voucher     Party            Product Qty Rate
43740  5/3/2018    9266  CUSTOMER  TIRML-BL-KG-17*23   2  NaN

In [26]:
sales_full_data[(sales_full_data["Product"] == "TIRML-BL-KG-17*23") & (sales_full_data["Qty"] == "2")]

             Date Voucher                Party            Product Qty Rate
2515   19/04/2017     510      S.HARI-CHITWELI  TIRML-BL-KG-17*23   2  125
10630    9/6/2017    2258                  Svr  TIRML-BL-KG-17*23   2  120
14974  14/07/2017    3252          R.D .STORES  TIRML-BL-KG-17*23   2  130
17775    4/8/2017    3885            ANR-VGIRI  TIRML-BL-KG-17*23   2  130
27952  20/10/2017    6016          R.D .STORES  TIRML-BL-KG-17*23   2  130
37241    1/1/2018    7895          R.D .STORES  TIRML-BL-KG-17*23   2  130
43740    5/3/2018    9266             CUSTOMER  TIRML-BL-KG-17*23   2  NaN
44857  14/03/2018    9528  SARAVANA TENKAYALA   TIRML-BL-KG-17*23   2  130
5706   14/05/2018    1195          R.D .STORES  TIRML-BL-KG-17*23   2  130
10256  18/06/2018    2132         TVT-CHITWELI  TIRML-BL-KG-17*23   2  130
12811    6/7/2018    2653          R.D .STORES  TIRML-BL-KG-17*23   2  130
17962  17/08/2018    3737  SRIRAMA PROVISIONS-  TIRML-BL-KG-17*23   2  130
19956  29/08/2018    4124          R.D .STORES  TIRML-BL-KG-17*23   2  130
23519  26/09/2018    4929          R.D .STORES  TIRML-BL-KG-17*23   2  130
25653  15/10/2018    5397          R.D .STORES  TIRML-BL-KG-17*23   2  130
29736  20/11/2018    6282       P.V.RAJA-VGIRI  TIRML-BL-KG-17*23   2  130

In [37]:
sales_full_data[sales_full_data["Rate"].isna()].fillna(value=130,inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_22188\3338442631.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_full_data[sales_full_data["Rate"].isna()].fillna(value=130,inplace=True)

In [35]:
sales_full_data.fillna(value=130,inplace=True)

In [36]:
sales_full_data.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [29]:
sales_full_data.drop_duplicates()

           Date Voucher     Party            Product Qty  Rate
43740  5/3/2018    9266  CUSTOMER  TIRML-BL-KG-17*23   2   130

In [30]:
sales_full_data.dropna(inplace=True)

In [31]:
sales_full_data[(sales_full_data["Voucher"] == "9266") & (sales_full_data["Product"] == "TIRML-BL-KG-17*23")]

           Date Voucher     Party            Product Qty  Rate
43740  5/3/2018    9266  CUSTOMER  TIRML-BL-KG-17*23   2   130

In [32]:
sales_full_data.dropna()

           Date Voucher     Party            Product Qty  Rate
43740  5/3/2018    9266  CUSTOMER  TIRML-BL-KG-17*23   2   130

In [33]:
sales_full_data.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate        int64
dtype: object

In [41]:
sales_full_data["Rate"]=pd.to_numeric(sales_full_data["Rate"])

In [37]:
sales_full_data["Date"]=pd.to_datetime(sales_full_data["Date"])

In [50]:
sales_full_data["Voucher"]=sales_full_data["Voucher"].astype('int64') 
sales_full_data["Qty"]=sales_full_data["Qty"].astype('int64') 
sales_full_data["Rate"]=sales_full_data["Rate"].astype('float')

In [49]:
sales_full_data.dtypes

Date       datetime64[ns]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

In [99]:
(sales_full_data["Date"].isna()) & (sales_full_data["Product"].notnull())

43740    False
dtype: bool

In [38]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16

# Task 2 Merge Function

In [40]:
students = pd.DataFrame({
    'roll_no': [1, 2, 3, 4],
    'name': ['Amit', 'Neha', 'Raj', 'Pooja']})

marks = pd.DataFrame({
    'roll_no': [1, 3, 4],
    'marks': [80, 75, 90]})

In [41]:
pd.merge(students,marks, on= "roll_no" , how="left")

   roll_no   name  marks
0        1   Amit   80.0
1        2   Neha    NaN
2        3    Raj   75.0
3        4  Pooja   90.0

In [5]:
orders = pd.DataFrame({
    'order_id': [101, 102, 103],
    'cust_id': [1, 2, 3]})

customers = pd.DataFrame({
    'cust_id': [1, 2],
    'cust_name': ['John', 'Emma']})

In [7]:
pd.merge(orders,customers,on="cust_id",how="right")

   order_id  cust_id cust_name
0       101        1      John
1       102        2      Emma

In [44]:
employees = pd.DataFrame({
    'emp_id': [1, 2, 3],
    'dept_id': [10, 20, 30]})
departments = pd.DataFrame({
    'dept_id': [10, 20],
    'dept_name': ['HR', 'IT']})

In [45]:
pd.merge(employees,departments,on="dept_id",how="left")

   emp_id  dept_id dept_name
0       1       10        HR
1       2       20        IT
2       3       30       NaN

In [46]:
products = pd.DataFrame({
    'pid': [1, 2, 3],
    'product_name': ['Pen', 'Book', 'Bag']})
sales = pd.DataFrame({
    'product_id': [1, 3],
    'quantity': [10, 5]})

In [47]:
pd.merge(products,sales,left_on ="pid",right_on ="product_id",how="left")

   pid product_name  product_id  quantity
0    1          Pen         1.0      10.0
1    2         Book         NaN       NaN
2    3          Bag         3.0       5.0

# Task 3 List Comprehension

In [48]:
squares=[0,1,2,3,4]
squares = [x**2 for x in range(5)]
print(squares)

[0, 1, 4, 9, 16]

In [49]:
numbers=[-3,4,-6,7,4,-2]
updated=[x if x > 0 else 0 for x in numbers]
print(updated)

[0, 4, 0, 7, 4, 0]

In [50]:
even=[ x for x in range(10) if x%2 ==0]
print(even)

[0, 2, 4, 6, 8]

# Task 4 Lambda Function Map , Filter , Reduce .

### Map

In [51]:
numbers=[2,3,4,5,6]
squared=list(map(lambda x: x**2,numbers))
print(squared)

[4, 9, 16, 25, 36]

### Filter

In [52]:
numbers=[1,2,3,4,5,6,7]
even=list(filter(lambda x: x%2 ==0,numbers))
print(even)

[2, 4, 6]

### Reduce

In [53]:
from functools import reduce

numbers=[1,2,3,4,5,6,7,8,9,10]
total=reduce(lambda a,b:a+b , numbers)
print(total)

55

#

# THE END ---------------------------------------------------